name: AirDelayPlugin
main: org.lostslvtt.airdelayplugin.AirDelayPlugin
version: 1.0
api-version: 1.18
commands:
  airdelay:
    usage: /airdelay reload
    permission: darateria.airbypass
permissions:
  darateria.airbypass:
    default: op
